### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by MayuraVerma** [hunspell/nuspell#7]
The issues can be of three types (put an X between the brackets):

- [ ] Bug reports
- [ ] Change request or feature request
- [X] Others, questions

# Other issues

Is there a alpha/beta release for nuspell in mac?

I can perform test for known test cases and create new test cases.

**Comment by PanderMusubi** [comment]
Dear @MayuraVerma,

Thank you for your message. We are not yet at an alpha stage. We have just completed the second milestone and have implemented the first generation of testing. Soon others will be able to test too and add their own tests, but not yet now. We will inform you when the time is there.

If you want, you can try to set up a development environment according to our [README](https://github.com/hunspell/nuspell/blob/master/README.md) and wiki on [IDE](https://github.com/hunspell/hunspell/wiki/IDE-Setup). Let us know if you manage to successfully run [test-test.sh](https://github.com/hunspell/misc-hunspell/blob/master/test-test.sh) This would be a good test for the project to see if someone outside of the development team can duplicate setting up a development environment, since we mainly work on Linux. We do have CI running for MacOS and Windows, by the way.

Best,

Pander
